# 多维数组 `numpy.ndarray` 的一些创建惯例

<https://numpy.org/devdocs/reference/routines.array-creation.html>

In [1]:
import numpy as np

## 从 Python 序列创建多维数组

In [2]:
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## 指定形状，创建未初始化的多维数组

In [3]:
shape = (2, 3, 4)
a = np.empty(shape)
a

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.06811626e-306],
        [1.42419938e-306, 7.56603881e-307, 8.45603440e-307,
         3.56043054e-307],
        [1.60219306e-306, 6.23059726e-307, 1.06811422e-306,
         3.56043054e-307]],

       [[1.37961641e-306, 6.23039354e-307, 6.23053954e-307,
         2.22522597e-306],
        [1.06810268e-306, 6.23052935e-307, 1.60218763e-306,
         8.34451504e-308],
        [1.78022342e-306, 8.06635958e-308, 1.42410974e-306,
         1.37954579e-306]]])

## 指定形状和初值，创建多维数组

特别的：

*   `numpy.ones(shape)` 等同于 `numpy.full(shape, 1)`
*   `numpy.zeros(shape)` 等同于 `numpy.full(shape, 0)`

In [4]:
shape, fill_value = (2, 3, 4), 1337
a = np.full(shape, fill_value)
a

array([[[1337, 1337, 1337, 1337],
        [1337, 1337, 1337, 1337],
        [1337, 1337, 1337, 1337]],

       [[1337, 1337, 1337, 1337],
        [1337, 1337, 1337, 1337],
        [1337, 1337, 1337, 1337]]])

## 指定形状，创建元素值在区间 `[0.0, 1.0)` 内随机的多维数组

In [5]:
shape = (2, 3, 4)
a = np.random.random(shape)
a

array([[[0.17780548, 0.23444197, 0.95398786, 0.45463596],
        [0.01899038, 0.04977293, 0.29508359, 0.44435492],
        [0.82205076, 0.9130233 , 0.32305042, 0.52844254]],

       [[0.76151968, 0.34011687, 0.26106286, 0.87656666],
        [0.87001087, 0.46300576, 0.0590908 , 0.95965922],
        [0.63143863, 0.9864612 , 0.91792817, 0.64468981]]])

## 指定初值函数和形状，创建自定义初值的多维数组

In [6]:
def fn(d1, d2, d3):
    return 100*(1+d1) + 10*(1+d2) + (1+d3)
shape = (2, 3, 4)
a = np.fromfunction(fn, shape)
a

array([[[111., 112., 113., 114.],
        [121., 122., 123., 124.],
        [131., 132., 133., 134.]],

       [[211., 212., 213., 214.],
        [221., 222., 223., 224.],
        [231., 232., 233., 234.]]])

## 多维数组的引用，不复制

In [7]:
a1 = np.empty([2, 3, 4])
a2 = a1

assert a2 is a1

## 多维数组的视图，浅复制，共用底层数据

In [8]:
a = np.empty([2, 3, 4])
v = a[:]

assert v is not a
assert v.base is a

## 多维数组的深复制

In [9]:
a1 = np.empty([2, 3, 4])
a2 = a1.copy()

assert a2 is not a1
assert a1.base is None
assert a2.base is None