# zhengrr's ipynb for NumPy

NumPy 官网 <https://numpy.org/>。

NumPy 提供了一个高性能的同构多维数组类 `numpy.ndarray`。

In [1]:
import numpy as np

print('NumPy version: ', np.__version__)

NumPy version:  1.19.2


## 多维数组 `numpy.ndarray` 的一些属性

In [2]:
a = np.array([[[111, 112, 113, 114],
               [121, 122, 123, 124],
               [131, 132, 133, 134]],
              [[211, 212, 213, 214],
               [221, 222, 223, 224],
               [231, 232, 233, 234]]])
a

array([[[111, 112, 113, 114],
        [121, 122, 123, 124],
        [131, 132, 133, 134]],

       [[211, 212, 213, 214],
        [221, 222, 223, 224],
        [231, 232, 233, 234]]])

### 多维数组的维度

In [3]:
a.ndim

3

### 多维数组的形状

In [4]:
a.shape

(2, 3, 4)

### 多维数组的元素总数

In [5]:
a.size

24

### 多维数组的元素类型

In [6]:
a.dtype

dtype('int32')

### 多维数组的元素大小

In [7]:
a.itemsize  # 等同于 a.dtype.itemsize

4

### 多维数组的底层数据

In [8]:
a.data

## 多维数组 `numpy.ndarray` 的一些创建方法

### 从 Python 列表或元组创建多维数组

In [9]:
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 指定形状，创建未初始化的多维数组

In [10]:
shape = (2, 3, 4)
a = np.empty(shape)
a

array([[[ 7.35818585e-312,  7.35783837e-312,  3.93545339e-310,
          6.88076602e-297],
        [ 2.27998501e-312,  3.10536870e-306,  1.33360356e+241,
          8.55291624e-310],
        [-5.00120720e-162,  4.12628713e-313,  2.70420353e-308,
         -3.38460682e+125]],

       [[ 3.69028917e+180,  4.99511698e-307,  7.76594725e-299,
          8.20618373e-304],
        [ 1.09403127e-303,  9.11571042e-304,  1.64122283e-303,
          1.28912425e+010],
        [ 1.09474191e-303,  6.98183975e-164,  3.72219086e-265,
          1.32625931e-279]]])

### 指定形状，创建元素值在区间 `[0.0, 1.0)` 内随机的多维数组

In [11]:
shape = (2, 3, 4)
a = np.random.random(shape)
a

array([[[0.50416248, 0.60382148, 0.44353237, 0.7754166 ],
        [0.91619497, 0.67851459, 0.78808074, 0.00261063],
        [0.61537289, 0.72270098, 0.78711342, 0.60583746]],

       [[0.77598969, 0.91816821, 0.15529691, 0.18021906],
        [0.95012032, 0.21446312, 0.28632115, 0.31808857],
        [0.76945894, 0.14965281, 0.1825585 , 0.82545201]]])

### 指定形状，创建全零的多维数组

In [12]:
shape = (2, 3, 4)
a = np.zeros(shape)
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 指定形状，创建全一的多维数组

In [13]:
shape = (2, 3, 4)
a = np.ones(shape)
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### 指定函数和形状，创建自定义的多维数组

In [14]:
def fn(d1, d2, d3):
    return 100*(1+d1) + 10*(1+d2) + (1+d3)
shape = (2, 3, 4)
a = np.fromfunction(fn, shape)
a

array([[[111., 112., 113., 114.],
        [121., 122., 123., 124.],
        [131., 132., 133., 134.]],

       [[211., 212., 213., 214.],
        [221., 222., 223., 224.],
        [231., 232., 233., 234.]]])

### 指定范围和步长，创建一维数组

In [15]:
start, stop, step = 3, 8, 2
a = np.arange(start, stop, step)
a

array([3, 5, 7])

### 指定范围和数目，创建一维数组

In [16]:
start, stop, num = 3, 8, 6
a = np.linspace(start, stop, num)
a

array([3., 4., 5., 6., 7., 8.])