# 基础操作

In [1]:
import numpy as np

## 统计

In [2]:
t = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print('求和 sum:', t.sum())
print('算数平均数 mean:', t.mean())
print('方差 var:', t.var())
print('标准差 std:', t.std())
print('最大值 max:', t.max())
print('最小值 min:', t.min())

求和 sum: 36
算数平均数 mean: 4.5
方差 var: 5.25
标准差 std: 2.29128784747792
最大值 max: 8
最小值 min: 1


## 张量逐元素与标量运算

In [3]:
t = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(t + 1)
#       -   *   /   //  %
#       <   <=  ==  >=  >   !=

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


## 同型张量逐元素四则运算

In [4]:
t1 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]]])
t2 = np.array([[[8, 7],
                [6, 5]],
               [[4, 3],
                [2, 1]]])
print(t1 + t2)
#        -   *   /

[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]
