# 矩阵（二维张量）

In [1]:
import numpy as np

m1 = np.array([[1, 3, 1],
               [1, 0, 0]])

m2 = np.array([[0, 0, 5],
               [7, 5, 0]])

m3 = np.array([[3, 1],
               [2, 1],
               [1, 0]])

## 同型矩阵的加（减）法

In [2]:
m1 + m2

array([[1, 3, 6],
       [8, 5, 0]])

## 矩阵数乘

In [3]:
m3 * 3

array([[9, 3],
       [6, 3],
       [3, 0]])

## 矩阵转置

In [4]:
m1.T

array([[1, 1],
       [3, 0],
       [1, 0]])

## 矩阵乘法

In [5]:
np.dot(m2, m3)

array([[ 5,  0],
       [31, 12]])