# zhengrr's ipynb for NumPy

NumPy 提供了一个高性能矩阵（多维数组）`numpy.ndarray`。

In [1]:
import numpy as np

## `numpy.ndarray` 的一些属性

In [2]:
a = np.array([[[111, 112, 113, 114],
               [121, 122, 123, 124],
               [131, 132, 133, 134]],
              [[211, 212, 213, 214],
               [221, 222, 223, 224],
               [231, 232, 233, 234]]])
print('矩阵维度 ndim:', a.ndim)
print('矩阵形状 shape:', a.shape)
print('元素总数 size:', a.size)
print('元素类型 dtype:', a.dtype)
print('元素大小 itemsize:', a.itemsize, 'byte(s)')
print('底层数据 data:', a.data)

矩阵维度 ndim: 3
矩阵形状 shape: (2, 3, 4)
元素总数 size: 24
元素类型 dtype: int32
元素大小 itemsize: 4 byte(s)
底层数据 data: <memory at 0x000002A80CAC1228>


## `numpy.ndarray` 的一些创建方法

### 从 Python 列表或元组创建

In [3]:
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 指定形状，创建未初始化的数组

In [4]:
a = np.empty((2, 3, 4))
print(a)

[[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.06811626e-306]
  [1.11261706e-306 7.56604561e-307 1.95821439e-306 1.60220800e-306]
  [1.06811422e-306 9.79063056e-307 9.79106514e-307 6.23054293e-307]]

 [[6.23053954e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307]
  [1.86921143e-306 6.23061763e-307 2.22522053e-306 1.11261095e-306]
  [1.42417221e-306 1.86922637e-306 1.69120281e-306 2.56765117e-312]]]


### 指定形状，创建值在区间 `[0.0, 1.0)` 内随机的数组

In [5]:
a = np.random.random((2, 3, 4))
print(a)

[[[0.76268208 0.7240419  0.40885872 0.34882788]
  [0.0442605  0.72303218 0.63849942 0.51980387]
  [0.45625101 0.17122628 0.44903432 0.25656585]]

 [[0.20192705 0.22692857 0.78222346 0.23914572]
  [0.35817346 0.72513337 0.43624467 0.6569813 ]
  [0.98802314 0.62527756 0.33971959 0.42990243]]]


### 指定形状，创建全零的数组

In [6]:
a = np.zeros((2, 3, 4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 指定形状，创建全一的数组

In [7]:
a = np.ones((2, 3, 4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 指定函数和形状，创建自定义数组

In [8]:
def f(d1, d2, d3):
    return 100*(1+d1) + 10*(1+d2) + (1+d3)
a = np.fromfunction(f, (2, 3, 4))
print(a)

[[[111. 112. 113. 114.]
  [121. 122. 123. 124.]
  [131. 132. 133. 134.]]

 [[211. 212. 213. 214.]
  [221. 222. 223. 224.]
  [231. 232. 233. 234.]]]


### 指定范围和步长，创建一维数组

In [9]:
a = np.arange(3, 8, 2)
print(a)

[3 5 7]


### 指定范围和数目，创建一维数组

In [10]:
a = np.linspace(3, 8, 6)
print(a)

[3. 4. 5. 6. 7. 8.]
