# zhengrr's ipynb for NumPy

NumPy 提供了一个高性能张量（多维数组）类 `numpy.ndarray`。

In [1]:
import numpy as np

## `numpy.ndarray` 的一些属性

In [2]:
t = np.array([[[111, 112, 113, 114],
               [121, 122, 123, 124],
               [131, 132, 133, 134]],
              [[211, 212, 213, 214],
               [221, 222, 223, 224],
               [231, 232, 233, 234]]])
print('张量维度 ndim:', t.ndim)
print('张量形状 shape:', t.shape)
print('元素总数 size:', t.size)
print('元素类型 dtype:', t.dtype)
print('元素大小 itemsize:', t.itemsize, 'byte(s)')
print('底层数据 data:', t.data)

张量维度 ndim: 3
张量形状 shape: (2, 3, 4)
元素总数 size: 24
元素类型 dtype: int32
元素大小 itemsize: 4 byte(s)
底层数据 data: <memory at 0x000001DA1BDE1048>


## `numpy.ndarray` 的一些创建方法

### 从 Python 列表或元组创建

In [3]:
t = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(t)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 指定形状，创建未初始化的张量

In [4]:
t = np.empty((2, 3, 4))
print(t)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 指定形状，创建元素值在区间 `[0.0, 1.0)` 内随机的张量

In [5]:
t = np.random.random((2, 3, 4))
print(t)

[[[0.99970799 0.00533903 0.47898918 0.83648084]
  [0.57283589 0.45471114 0.33795179 0.94772937]
  [0.24533198 0.0010738  0.21361401 0.38057651]]

 [[0.44952605 0.72193232 0.68048136 0.21785121]
  [0.24655226 0.6958703  0.41063301 0.6828236 ]
  [0.50634843 0.90795255 0.35215074 0.86261591]]]


### 指定形状，创建全零的张量

In [6]:
t = np.zeros((2, 3, 4))
print(t)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 指定形状，创建全一的张量

In [7]:
t = np.ones((2, 3, 4))
print(t)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 指定函数和形状，创建自定义张量

In [8]:
def f(d1, d2, d3):
    return 100*(1+d1) + 10*(1+d2) + (1+d3)
t = np.fromfunction(f, (2, 3, 4))
print(t)

[[[111. 112. 113. 114.]
  [121. 122. 123. 124.]
  [131. 132. 133. 134.]]

 [[211. 212. 213. 214.]
  [221. 222. 223. 224.]
  [231. 232. 233. 234.]]]


### 指定范围和步长，创建数组（一阶张量）

In [9]:
a = np.arange(3, 8, 2)
print(a)

[3 5 7]


### 指定范围和数目，创建数组（一阶张量）

In [10]:
a = np.linspace(3, 8, 6)
print(a)

[3. 4. 5. 6. 7. 8.]
