# zhengrr's ipynb for NumPy

NumPy 提供了一个高性能张量（多维数组）类 `numpy.ndarray`。

In [1]:
import numpy as np

print('NumPy version: ', np.__version__)

NumPy version:  1.18.3


## `numpy.ndarray` 的一些属性

In [2]:
t = np.array([[[111, 112, 113, 114],
               [121, 122, 123, 124],
               [131, 132, 133, 134]],
              [[211, 212, 213, 214],
               [221, 222, 223, 224],
               [231, 232, 233, 234]]])
print('张量维度 ndim:', t.ndim)
print('张量形状 shape:', t.shape)
print('元素总数 size:', t.size)
print('元素类型 dtype:', t.dtype)
print('元素大小 itemsize:', t.itemsize, 'byte(s)')
print('底层数据 data:', t.data)

张量维度 ndim: 3
张量形状 shape: (2, 3, 4)
元素总数 size: 24
元素类型 dtype: int32
元素大小 itemsize: 4 byte(s)
底层数据 data: <memory at 0x000002462AA12228>


## `numpy.ndarray` 的一些创建方法

### 从 Python 列表或元组创建

In [3]:
t = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(t)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 指定形状，创建未初始化的张量

In [4]:
t = np.empty((2, 3, 4))
print(t)

[[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.06811626e-306]
  [1.11261706e-306 7.56604561e-307 1.95821439e-306 1.60220800e-306]
  [1.06811422e-306 9.79063056e-307 9.79106514e-307 6.23054293e-307]]

 [[6.23053954e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307]
  [1.86921143e-306 6.23061763e-307 2.22522053e-306 1.11261095e-306]
  [8.45590539e-307 2.22520695e-306 1.95820216e-306 2.56765117e-312]]]


### 指定形状，创建元素值在区间 `[0.0, 1.0)` 内随机的张量

In [5]:
t = np.random.random((2, 3, 4))
print(t)

[[[0.34175043 0.33320893 0.20732985 0.10781836]
  [0.32714834 0.9759223  0.13836886 0.66817142]
  [0.1753397  0.42323911 0.50739942 0.05359363]]

 [[0.76864958 0.3905501  0.54647413 0.84013096]
  [0.51095018 0.94135855 0.99600297 0.76429081]
  [0.99228267 0.01208542 0.62265764 0.33823604]]]


### 指定形状，创建全零的张量

In [6]:
t = np.zeros((2, 3, 4))
print(t)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 指定形状，创建全一的张量

In [7]:
t = np.ones((2, 3, 4))
print(t)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 指定函数和形状，创建自定义张量

In [8]:
def f(d1, d2, d3):
    return 100*(1+d1) + 10*(1+d2) + (1+d3)
t = np.fromfunction(f, (2, 3, 4))
print(t)

[[[111. 112. 113. 114.]
  [121. 122. 123. 124.]
  [131. 132. 133. 134.]]

 [[211. 212. 213. 214.]
  [221. 222. 223. 224.]
  [231. 232. 233. 234.]]]


### 指定范围和步长，创建数组（一阶张量）

In [9]:
a = np.arange(3, 8, 2)
print(a)

[3 5 7]


### 指定范围和数目，创建数组（一阶张量）

In [10]:
a = np.linspace(3, 8, 6)
print(a)

[3. 4. 5. 6. 7. 8.]
